version: "3.9"

services:
  web:
    container_name: "Django"
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - service
    depends_on:
      - db

volumes:
  static_volume:
  media_volume:

networks:
  service:
    driver: bridge